version: '3'

services:
  postgres:
    image: kartoza/postgis:11.0-2.5
    ports:
      - "5432:5432"
    volumes:
      - "wazimap-data13:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=wazimap_ng
      - POSTGRES_PASS=wazimap_ng
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,pg_trgm
volumes:
  wazimap-data13:
