site_name: wazimap_ng
site_description: Wazimap Next Generation
repo_url: https://github.com/adieyal/wazimap-ng
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/adieyal">adieyal</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
